server.port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost/authserver
    username: authserver
    password: authserver
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        hbm2ddl:
          auto: validate
    hibernate:
      ddl-auto: none
          
